"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WhatsappMessageTypeEnum = void 0;
var WhatsappMessageTypeEnum;
(function (WhatsappMessageTypeEnum) {
    WhatsappMessageTypeEnum["TEXT"] = "text";
    WhatsappMessageTypeEnum["IMAGE"] = "image";
    WhatsappMessageTypeEnum["VIDEO"] = "video";
    WhatsappMessageTypeEnum["VOICE"] = "voice";
    WhatsappMessageTypeEnum["AUDIO"] = "audio";
    WhatsappMessageTypeEnum["DOCUMENT"] = "document";
    WhatsappMessageTypeEnum["STICKER"] = "sticker";
    WhatsappMessageTypeEnum["LOCATION"] = "location";
    WhatsappMessageTypeEnum["EVENT"] = "event";
    WhatsappMessageTypeEnum["PROTOCOL"] = "protocol";
    WhatsappMessageTypeEnum["TEMPLATE"] = "template";
    WhatsappMessageTypeEnum["CONTACT"] = "contact";
    WhatsappMessageTypeEnum["CONTACT_ARRAY"] = "contact_array";
    WhatsappMessageTypeEnum["LIVE_LOCATION"] = "live_location";
    WhatsappMessageTypeEnum["GROUP_INVITE"] = "group_invite";
    WhatsappMessageTypeEnum["LIST"] = "list";
    WhatsappMessageTypeEnum["LIST_RESPONSE"] = "list_response";
    WhatsappMessageTypeEnum["BUTTONS"] = "buttons";
    WhatsappMessageTypeEnum["BUTTONS_RESPONSE"] = "buttons_response";
    WhatsappMessageTypeEnum["REACTION"] = "reaction";
    WhatsappMessageTypeEnum["POLL"] = "poll";
    WhatsappMessageTypeEnum["POLL_UPDATE"] = "poll_update";
    WhatsappMessageTypeEnum["ORDER"] = "order";
    WhatsappMessageTypeEnum["INTERACTIVE"] = "interactive";
    WhatsappMessageTypeEnum["CALL"] = "call";
    WhatsappMessageTypeEnum["PTV"] = "ptv";
    WhatsappMessageTypeEnum["LOTTIE_STICKER"] = "lottie_sticker";
    WhatsappMessageTypeEnum["ALBUM"] = "album";
    WhatsappMessageTypeEnum["UNKNOWN"] = "unknown";
})(WhatsappMessageTypeEnum || (exports.WhatsappMessageTypeEnum = WhatsappMessageTypeEnum = {}));
