name: Deploy Brokerin
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: "sa-east-1"

      - name: Generate Deployment Package
        # We only zip what is necessary to run the app: dist, package files, and the Procfile
        run: zip -r deploy.zip dist package.json package-lock.json Procfile

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          session_token: ${{ env.AWS_SESSION_TOKEN }}
          application_name: "brokerin"
          environment_name: "Brokerin-env"
          version_label: "deploy-${{ github.sha }}"
          region: "sa-east-1"
          deployment_package: "deploy.zip"